#ifndef __N3D_UTIL_H_
#define __N3D_UTIL_H_

#include "D3D8.h"

D3DCOLOR _RGB_To_D3DCOLOR(COLORREF cr, float fAlpha);
COLORREF _D3DCOLOR_To_RGB(D3DCOLOR& cr);
COLORREF _D3DCOLORVALUE_To_RGB(D3DCOLORVALUE& cr);
D3DCOLORVALUE _RGB_To_D3DCOLORVALUE(COLORREF cr, float fAlpha);

#endif __N3D_UTIL_H_