//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by N3Indoor.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_N3INDOTYPE                  129
#define IDD_PROPERTY                    130
#define IDD_BROWSE_PATH                 131
#define IDD_SCENE_GRAPH                 132
#define IDI_PVOLUMN                     134
#define IDD_COMPUTING                   135
#define IDD_SHAPE_TYPE                  136
#define IDI_SHAPE                       137
#define IDI_VOL_YT                      146
#define IDI_VOL_ZB                      147
#define IDI_VOL_XL                      148
#define IDI_VOL_YB                      149
#define IDI_VOL_XR                      150
#define IDI_VOL_ZF                      151
#define IDC_TRANSFORM                   152
#define IDC_SELECT                      156
#define IDD_SHAPE_LIST                  163
#define IDD_UNUSED_FILES                164
#define IDD_BASE                        165
#define IDD_MAKE_NPCPATH                170
#define IDD_EDIT_EVENT                  171
#define IDD_REGEN_USER                  172
#define IDD_ENVIRON_SOUND               173
#define IDD_FLOORSET                    174
#define IDC_FPS                         1000
#define IDC_BUTTON_RESOURCE_PATH        1001
#define IDC_EDIT_RESOURCE_PATH          1002
#define IDC_EDIT                        1003
#define IDC_COMPILE                     1004
#define IDC_ACTIVE                      1005
#define IDC_STATE_PVOLUMN               1006
#define IDC_STATE_SHAPE                 1007
#define IDC_ADD_SHAPE                   1012
#define IDC_ADD_COLLISION               1013
#define IDC_EDIT_RESOURCE_NAME          1015
#define IDC_BTN_CREATE_VOL              1026
#define IDC_BTN_DELETE                  1027
#define IDC_LIST_SELECT                 1028
#define IDC_BTN_CREATE_GATE1            1029
#define IDC_BTN_CREATE_GATE2            1030
#define IDC_BTN_CREATE_GATE3            1031
#define IDC_BTN_CREATE_GATE4            1032
#define IDC_BTN_CREATE_GATE5            1033
#define IDC_BTN_CREATE_GATE6            1034
#define IDC_TOTAL_MOVEX                 1035
#define IDC_LIST_LINKTO                 1036
#define IDC_LIST_LINKED                 1037
#define IDC_BTN_LINKED_DELETE           1038
#define IDC_LIST_SHAPES                 1039
#define IDC_FILELIST                    1040
#define IDC_BTN_LINKTO_VOLUME           1040
#define IDC_INDI_PICK                   1040
#define IDC_SYNCH_FOLDERS               1041
#define IDC_BTN_SHAPE_DELETE            1041
#define IDC_BROWSE_TREE                 1042
#define IDC_TOTAL_MOVEY                 1042
#define IDC_INDI_MOVE                   1042
#define IDC_TREE_OBJ                    1043
#define IDC_TOTAL_MOVEZ                 1043
#define IDC_INDI_ROTATE                 1043
#define IDC_PREVIEW                     1044
#define IDC_TOTAL_SCALEX                1044
#define IDC_INDI_SCALE                  1044
#define IDC_TOTAL_SCALEY                1045
#define IDC_BUTTON_FILE_NAME            1046
#define IDC_OK                          1047
#define IDC_TOTAL_SCALEZ                1047
#define IDC_RADIO_PARTIAL               1048
#define IDC_TOTAL_SCALEXYZ              1048
#define IDC_RADIO_NONEPARTIAL           1049
#define IDC_PROGRESS                    1051
#define IDC_TOTAL_MOVE_X                1052
#define IDC_TOTAL_MOVE_Z                1053
#define IDC_SELECT_VOL_TEXT             1054
#define IDC_BTN_SORT                    1062
#define IDC_LIST_OBJ                    1063
#define IDC_LIST_FILES                  1064
#define IDC_DELETE                      1065
#define ID_CANCEL                       1066
#define IDC_LIST_INVALID_OBJECTS        1067
#define IDC_TOTAL_MOVE_Y                1068
#define IDC_E_NAME                      1070
#define IDC_LP_TRANSFORM                1071
#define IDC_LP_CAMERA                   1072
#define IDC_LP_LIGHT                    1073
#define IDC_CB_PART_SHAPE               1074
#define IDC_LP_SHAPE                    1075
#define IDC_CB_PART_CHARACTE            1076
#define IDC_CB_LOD                      1077
#define IDC_LP_CHR                      1078
#define IDC_LP_CHR_PART                 1079
#define IDC_CB_PLUG_CHARACTER           1080
#define IDC_LP_CHR_PLUG                 1081
#define IDC_LP_MATERIAL                 1082
#define IDC_VIEW_SELECTED_TOTAL_SHAPE   1091
#define IDC_COMBO_FLOOR                 1092
#define IDC_SET_FLOOR                   1093
#define IDC_CHECK_FLOOR                 1094
#define IDC_DELETE_FLOOR                1095
#define IDC_FLOOR_NUMBER                1096
#define ID_FILE_OPEN_GAMEDATA           32771
#define ID_FILE_SAVE_WORKSHOP           32772
#define ID_FILE_SAVE_GAMEDATA           32773
#define ID_FILE_WORKSHOP_OPEN           32774
#define ID_VIEW_SOURCEOBJECT            32775
#define ID_CURSOR_SELECT                32776
#define ID_CURSOR_POS                   32777
#define ID_CURSOR_ROTATE                32778
#define ID_CURSOR_MAKE_NPCPATH          32779
#define ID_CURSOR_EDIT_EVENT            32780
#define ID_CURSOR_REGEN_USER            32781
#define ID_CURSOR_SOUND                 32782
#define ID_CURSOR_SCALE                 32783
#define ID_TIP_FOCUS_SELOBJ             32784
#define ID_TIP_FOCUS_ALL                32785
#define ID_TIP_DELETE_OBJ               32786
#define ID_TIP_NEXT_SHAPE               32788
#define ID_TIP_DELETE_UNUSED_FILES      32789
#define ID_VIEW_OUTPUTOBJECT            32790
#define ID_EDIT_PROPERTY                32791
#define ID_TOTAL_PROPERTY_TOOL          32793
#define ID_FILE_SERVER_DATA             32794
#define IDS_TOTAL_SHEET                 61205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
